import { CountryCode } from "libphonenumber-js";

export type Country = { ddi: string; name: string; abbreviation: CountryCode };

export default [
  { ddi: "+55", name: "Brasil", abbreviation: "BR" },
  { ddi: "+93", name: "Afeganistão", abbreviation: "AF" },
  { ddi: "+355", name: "Albânia", abbreviation: "AL" },
  { ddi: "+49", name: "Alemanha", abbreviation: "DE" },
  { ddi: "+376", name: "Andorra", abbreviation: "AD" },
  { ddi: "+244", name: "Angola", abbreviation: "AO" },
  { ddi: "+1264", name: "Anguilla", abbreviation: "AI" },
  { ddi: "+1268", name: "Antigua e Barbuda", abbreviation: "AG" },
  { ddi: "+54", name: "Argentina", abbreviation: "AR" },
  { ddi: "+213", name: "Argélia", abbreviation: "DZ" },
  { ddi: "+374", name: "Armênia", abbreviation: "AM" },
  { ddi: "+297", name: "Aruba", abbreviation: "AW" },
  { ddi: "+966", name: "Arábia Saudita", abbreviation: "SA" },
  { ddi: "+61", name: "Austrália", abbreviation: "AU" },
  { ddi: "+994", name: "Azerbaijão", abbreviation: "AZ" },
  { ddi: "+1242", name: "Bahamas", abbreviation: "BS" },
  { ddi: "+973", name: "Bahrain", abbreviation: "BH" },
  { ddi: "+880", name: "Bangladesh", abbreviation: "BD" },
  { ddi: "+1246", name: "Barbados", abbreviation: "BB" },
  { ddi: "+501", name: "Belize", abbreviation: "BZ" },
  { ddi: "+229", name: "Benin", abbreviation: "BJ" },
  { ddi: "+1441", name: "Bermudas", abbreviation: "BM" },
  { ddi: "+375", name: "Bielo-Rússia", abbreviation: "BY" },
  { ddi: "+591", name: "Bolívia", abbreviation: "BO" },
  { ddi: "+267", name: "Botswana", abbreviation: "BW" },
  { ddi: "+673", name: "Brunei", abbreviation: "BN" },
  { ddi: "+359", name: "Bulgária", abbreviation: "BG" },
  { ddi: "+226", name: "Burkina Faso", abbreviation: "BF" },
  { ddi: "+257", name: "Burundi", abbreviation: "BI" },
  { ddi: "+975", name: "Butão", abbreviation: "BT" },
  { ddi: "+32", name: "Bélgica", abbreviation: "BE" },
  { ddi: "+387", name: "Bósnia e Herzegovina", abbreviation: "BA" },
  { ddi: "+237", name: "Camarões", abbreviation: "CM" },
  { ddi: "+855", name: "Camboja", abbreviation: "KH" },
  { ddi: "+1", name: "Canadá", abbreviation: "CA" },
  { ddi: "+974", name: "Catar", abbreviation: "QA" },
  { ddi: "+7", name: "Cazaquistão", abbreviation: "KZ" },
  { ddi: "+235", name: "Chade", abbreviation: "TD" },
  { ddi: "+56", name: "Chile", abbreviation: "CL" },
  { ddi: "+86", name: "China", abbreviation: "CN" },
  { ddi: "+357", name: "Chipre", abbreviation: "CY" },
  { ddi: "+65", name: "Cingapura", abbreviation: "SG" },
  { ddi: "+57", name: "Colômbia", abbreviation: "CO" },
  { ddi: "+269", name: "Comores", abbreviation: "KM" },
  { ddi: "+850", name: "Coreia do Norte", abbreviation: "KP" },
  { ddi: "+82", name: "Coreia do Sul", abbreviation: "KR" },
  { ddi: "+506", name: "Costa Rica", abbreviation: "CR" },

  { ddi: "+385", name: "Croácia", abbreviation: "HR" },
  { ddi: "+53", name: "Cuba", abbreviation: "CU" },
  { ddi: "+420", name: "Czechia", abbreviation: "CZ" },
  { ddi: "+225", name: "Côte d’Ivoire", abbreviation: "CI" },
  { ddi: "+45", name: "Dinamarca", abbreviation: "DK" },
  { ddi: "+253", name: "Djibouti", abbreviation: "DJ" },
  { ddi: "+1767", name: "Dominica", abbreviation: "DM" },
  { ddi: "+20", name: "Egito", abbreviation: "EG" },
  { ddi: "+503", name: "El Salvador", abbreviation: "SV" },
  { ddi: "+971", name: "Emirados Árabes Unidos", abbreviation: "AE" },
  { ddi: "+593", name: "Equador", abbreviation: "EC" },
  { ddi: "+291", name: "Eritreia", abbreviation: "ER" },
  { ddi: "+421", name: "Eslováquia", abbreviation: "SK" },
  { ddi: "+386", name: "Eslovênia", abbreviation: "SI" },
  { ddi: "+34", name: "Espanha", abbreviation: "ES" },
  { ddi: "+1", name: "Estados Unidos", abbreviation: "US" },
  { ddi: "+372", name: "Estônia", abbreviation: "EE" },
  { ddi: "+268", name: "Eswatini", abbreviation: "SZ" },
  { ddi: "+251", name: "Etiópia", abbreviation: "ET" },
  { ddi: "+679", name: "Fiji", abbreviation: "FJ" },
  { ddi: "+63", name: "Filipinas", abbreviation: "PH" },
  { ddi: "+358", name: "Finlândia", abbreviation: "FI" },
  { ddi: "+33", name: "França", abbreviation: "FR" },
  { ddi: "+241", name: "Gabão", abbreviation: "GA" },
  { ddi: "+233", name: "Gana", abbreviation: "GH" },
  { ddi: "+995", name: "Georgia", abbreviation: "GE" },
  { ddi: "+350", name: "Gibraltar", abbreviation: "GI" },
  { ddi: "+1473", name: "Grenada", abbreviation: "GD" },
  { ddi: "+30", name: "Grécia", abbreviation: "GR" },
  { ddi: "+502", name: "Guatemala", abbreviation: "GT" },
  { ddi: "+44", name: "Guernsey", abbreviation: "GG" },
  { ddi: "+592", name: "Guiana", abbreviation: "GY" },
  { ddi: "+224", name: "Guiné", abbreviation: "GN" },
  { ddi: "+240", name: "Guiné Equatorial", abbreviation: "GQ" },
  { ddi: "+245", name: "Guiné-bissau", abbreviation: "GW" },
  { ddi: "+220", name: "Gâmbia", abbreviation: "GM" },
  { ddi: "+509", name: "Haiti", abbreviation: "HT" },
  { ddi: "+504", name: "Honduras", abbreviation: "HN" },
  { ddi: "+36", name: "Hungria", abbreviation: "HU" },
  { ddi: "+44", name: "Ilha de Man", abbreviation: "IM" },
  { ddi: "+358", name: "Ilhas Aland", abbreviation: "AX" },
  { ddi: "+1345", name: "Ilhas Cayman", abbreviation: "KY" },
  { ddi: "+500", name: "Ilhas Falkland", abbreviation: "FK" },
  { ddi: "+677", name: "Ilhas Salomão", abbreviation: "SB" },
  { ddi: "+1649", name: "Ilhas Turks e Caicos", abbreviation: "TC" },
  { ddi: "+1284", name: "Ilhas Virgens Britânicas", abbreviation: "VG" },
  { ddi: "+62", name: "Indonésia", abbreviation: "ID" },
  { ddi: "+228", name: "Ir", abbreviation: "TG" },
  { ddi: "+964", name: "Iraque", abbreviation: "IQ" },
  { ddi: "+353", name: "Irlanda", abbreviation: "IE" },
  { ddi: "+98", name: "Irã", abbreviation: "IR" },
  { ddi: "+354", name: "Islândia", abbreviation: "IS" },
  { ddi: "+972", name: "Israel", abbreviation: "IL" },
  { ddi: "+39", name: "Itália", abbreviation: "IT" },
  { ddi: "+967", name: "Iémen", abbreviation: "YE" },
  { ddi: "+1876", name: "Jamaica", abbreviation: "JM" },
  { ddi: "+81", name: "Japão", abbreviation: "JP" },
  { ddi: "+44", name: "Jersey", abbreviation: "JE" },
  { ddi: "+962", name: "Jordânia", abbreviation: "JO" },
  { ddi: "+965", name: "Kuwait", abbreviation: "KW" },
  { ddi: "+856", name: "Laos", abbreviation: "LA" },
  { ddi: "+266", name: "Lesoto", abbreviation: "LS" },
  { ddi: "+371", name: "Letônia", abbreviation: "LV" },
  { ddi: "+231", name: "Libéria", abbreviation: "LR" },
  { ddi: "+423", name: "Liechtenstein", abbreviation: "LI" },
  { ddi: "+370", name: "Lituânia", abbreviation: "LT" },
  { ddi: "+352", name: "Luxemburgo", abbreviation: "LU" },
  { ddi: "+961", name: "Líbano", abbreviation: "LB" },
  { ddi: "+218", name: "Líbia", abbreviation: "LY" },
  { ddi: "+389", name: "Macedônia do Norte", abbreviation: "MK" },
  { ddi: "+261", name: "Madagáscar", abbreviation: "MG" },
  { ddi: "+265", name: "Malawi", abbreviation: "MW" },
  { ddi: "+960", name: "Maldivas", abbreviation: "MV" },
  { ddi: "+223", name: "Mali", abbreviation: "ML" },
  { ddi: "+356", name: "Malta", abbreviation: "MT" },
  { ddi: "+60", name: "Malásia", abbreviation: "MY" },
  { ddi: "+212", name: "Marrocos", abbreviation: "MA" },
  { ddi: "+222", name: "Mauritânia", abbreviation: "MR" },
  { ddi: "+230", name: "Maurício", abbreviation: "MU" },
  { ddi: "+95", name: "Mianmar (Birmânia)", abbreviation: "MM" },
  { ddi: "+691", name: "Micronésia", abbreviation: "FM" },
  { ddi: "+373", name: "Moldova", abbreviation: "MD" },
  { ddi: "+976", name: "Mongólia", abbreviation: "MN" },
  { ddi: "+382", name: "Montenegro", abbreviation: "ME" },
  { ddi: "+1664", name: "Montserrat", abbreviation: "MS" },
  { ddi: "+258", name: "Moçambique", abbreviation: "MZ" },
  { ddi: "+52", name: "México", abbreviation: "MX" },
  { ddi: "+377", name: "Mônaco", abbreviation: "MC" },
  { ddi: "+264", name: "Namibia", abbreviation: "NA" },
  { ddi: "+977", name: "Nepal", abbreviation: "NP" },
  { ddi: "+505", name: "Nicarágua", abbreviation: "NI" },
  { ddi: "+234", name: "Nigéria", abbreviation: "NG" },
  { ddi: "+47", name: "Noruega", abbreviation: "NO" },
  { ddi: "+64", name: "Nova Zelândia", abbreviation: "NZ" },

  { ddi: "+227", name: "Níger", abbreviation: "NE" },
  { ddi: "+968", name: "Omã", abbreviation: "OM" },
  { ddi: "+680", name: "Palau", abbreviation: "PW" },
  { ddi: "+507", name: "Panamá", abbreviation: "PA" },
  { ddi: "+675", name: "Papua Nova Guiné", abbreviation: "PG" },
  { ddi: "+92", name: "Paquistão", abbreviation: "PK" },
  { ddi: "+595", name: "Paraguai", abbreviation: "PY" },
  { ddi: "+31", name: "Países Baixos", abbreviation: "NL" },
  { ddi: "+90", name: "Peru", abbreviation: "TR" },
  { ddi: "+51", name: "Peru", abbreviation: "PE" },
  { ddi: "+689", name: "Polinésia Francesa", abbreviation: "PF" },
  { ddi: "+48", name: "Polônia", abbreviation: "PL" },
  { ddi: "+1939", name: "Porto Rico", abbreviation: "PR" },
  { ddi: "+351", name: "Portugal", abbreviation: "PT" },
  { ddi: "+996", name: "Quirguistão", abbreviation: "KG" },
  { ddi: "+254", name: "Quênia", abbreviation: "KE" },
  { ddi: "+852", name: "RAE de Hong Kong China", abbreviation: "HK" },
  { ddi: "+853", name: "RAE de Macau China", abbreviation: "MO" },
  { ddi: "+44", name: "Reino Unido", abbreviation: "GB" },
  { ddi: "+236", name: "República Centro-Africana", abbreviation: "CF" },
  { ddi: "+243", name: "República Democrática do Congo", abbreviation: "CD" },
  { ddi: "+1", name: "República Dominicana", abbreviation: "DO" },
  { ddi: "+242", name: "República do Congo", abbreviation: "CG" },
  { ddi: "+40", name: "Romênia", abbreviation: "RO" },
  { ddi: "+250", name: "Ruanda", abbreviation: "RW" },
  { ddi: "+7", name: "Rússia", abbreviation: "RU" },
  { ddi: "+685", name: "Samoa", abbreviation: "WS" },
  { ddi: "+378", name: "San Marino", abbreviation: "SM" },
  { ddi: "+290", name: "Santa Helena", abbreviation: "SH" },
  { ddi: "+1758", name: "Santa Lúcia", abbreviation: "LC" },
  { ddi: "+221", name: "Senegal", abbreviation: "SN" },
  { ddi: "+232", name: "Serra Leoa", abbreviation: "SL" },
  { ddi: "+248", name: "Seychelles", abbreviation: "SC" },
  { ddi: "+252", name: "Somália", abbreviation: "SO" },
  { ddi: "+94", name: "Sri Lanka", abbreviation: "LK" },
  { ddi: "+249", name: "Sudão", abbreviation: "SD" },
  { ddi: "+597", name: "Suriname", abbreviation: "SR" },
  { ddi: "+46", name: "Suécia", abbreviation: "SE" },
  { ddi: "+41", name: "Suíça", abbreviation: "CH" },
  { ddi: "+1869", name: "São Cristóvão e Nevis", abbreviation: "KN" },
  { ddi: "+239", name: "São Tomé e Príncipe", abbreviation: "ST" },
  { ddi: "+1784", name: "São Vicente e Granadinas", abbreviation: "VC" },
  { ddi: "+381", name: "Sérvia", abbreviation: "RS" },
  { ddi: "+963", name: "Síria", abbreviation: "SY" },
  { ddi: "+66", name: "Tailândia", abbreviation: "TH" },
  { ddi: "+886", name: "Taiwan", abbreviation: "TW" },
  { ddi: "+992", name: "Tajiquistão", abbreviation: "TJ" },
  { ddi: "+255", name: "Tanzânia", abbreviation: "TZ" },
  { ddi: "+670", name: "Timor-Leste", abbreviation: "TL" },
  { ddi: "+676", name: "Tonga", abbreviation: "TO" },
  { ddi: "+1868", name: "Trinidad e Tobago", abbreviation: "TT" },
  { ddi: "+216", name: "Tunísia", abbreviation: "TN" },
  { ddi: "+993", name: "Turcomenistão", abbreviation: "TM" },
  { ddi: "+380", name: "Ucrânia", abbreviation: "UA" },
  { ddi: "+256", name: "Uganda", abbreviation: "UG" },
  { ddi: "+598", name: "Uruguai", abbreviation: "UY" },
  { ddi: "+998", name: "Uzbequistão", abbreviation: "UZ" },
  { ddi: "+678", name: "Vanuatu", abbreviation: "VU" },
  { ddi: "+58", name: "Venezuela", abbreviation: "VE" },
  { ddi: "+84", name: "Vietnã", abbreviation: "VN" },
  { ddi: "+263", name: "Zimbábue", abbreviation: "ZW" },
  { ddi: "+260", name: "Zâmbia", abbreviation: "ZM" },
  { ddi: "+238", name: "cabo Verde", abbreviation: "CV" },
  { ddi: "+27", name: "África do Sul", abbreviation: "ZA" },
  { ddi: "+43", name: "Áustria", abbreviation: "AT" },
  { ddi: "+91", name: "Índia", abbreviation: "IN" },
] as const;
